activeWorkspaceOnFocusChange = true
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = true
displayMode = 'static'
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = false
enableSpaceControlTilesAnimations = false
enableSwipeGestures = true
enableWorkspaceTransitions = false
focusDown = 'cmd+ctrl+opt+j'
focusFrontmostWindow = false
focusLeft = 'cmd+ctrl+opt+h'
focusNextWorkspaceApp = 'cmd+`'
focusNextWorkspaceWindow = 'opt+`'
focusRight = 'cmd+ctrl+opt+l'
focusUp = 'cmd+ctrl+opt+k'
keepUnassignedAppsOnSwitch = false
loopWorkspaces = true
loopWorkspacesOnAllDisplays = false
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = true
runScriptAfterWorkspaceChange = ''
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFloatingNotifications = true
showMenuBarIcon = false
showMenuBarTitle = true
showSpaceControl = 'cmd+ctrl+opt+space'
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlHideEmptyWorkspaces = true
spaceControlNumberOfColumns = 0
spaceControlUpdateScreenshotsOnOpen = false
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'nextWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'previousWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToNextProfile = 'cmd+ctrl+opt+f12'
switchToNextWorkspace = 'cmd+ctrl+opt+e'
switchToPreviousWorkspace = 'cmd+ctrl+opt+q'
switchWorkspaceOnCursorScreen = false
switchWorkspaceWhenPipCloses = true
toggleTheFocusedAppFloating = 'opt+shift+space'
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999

[[floatingApps]]
bundleIdentifier = 'com.apple.TextEdit'
iconPath = '/System/Applications/TextEdit.app/Contents/Resources/AppIcon.icns'
name = 'TextEdit'